services:
  big-agi:
    image: ghcr.io/enricoros/big-agi:latest
    ports:
      - "3000:3000"
    command: [ "next", "start", "-p", "3000" ]
  workerservice:
    build:
      context: ./WorkerService/WorkerService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - .env.workerservice.example

  client:
    image: nginx:1.27.0-alpine
    container_name: LibreChat-NGINX
    ports:
      - 80:80
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.custom.conf:/etc/nginx/conf.d/default.conf